version: 2
updates:
  # Fetch and update latest `pub` packages
  - package-ecosystem: pub 
    directory: '/'
    schedule:
      interval: daily
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
