name: witnet
description: A library to interface with the Witnet Protocol.
version: 0.1.1
# homepage: https://github.com/parodyBit/witnet.dart
# author: parodyBit

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
dependencies:
  cbor: ^4.0.2
  http: ^0.13.3
  hex: ^0.2.0
  pointycastle: ^3.1.3
  path: ^1.4.1
  web_socket_channel: ^2.1.0
  async: ^2.6.1
