name: witnet
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com
# author: parodyBit

environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
dependencies: 
  hex: ^0.2.0
  pointycastle: ^3.1.3
  path: ^1.4.1
